dist: xenial

sudo: required

language: python

python: 3.7

services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10-postgis-2.4

env:
  global:
  - DJANGO_SETTINGS_MODULE=zac.conf.settings
  - SECRET_KEY=dummy
  - DB_PASSWORD=
  - DB_USER=postgres

install:
  - pip install -r requirements.txt
  - pip install codecov
  - npm install

script:
  - python src/manage.py collectstatic --noinput --link
  - coverage run src/manage.py test src

after_success:
  - codecov
