# Inspired by https://docs.docker.com/compose/django/
version: '3.4'

services:
  redis:
    image: redis
  db:
    image: postgres
  web:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=zac.conf.docker
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
      - redis
  nginx:
    image: nginx:1.15
    ports:
      - 8080:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
