version: '3.4'

services:
  db:
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    volumes:
      - static:/app/static

  nginx:
    volumes:
      - nginx_logs:/var/log/nginx
      - static:/static

volumes:
  postgres_data:
  static:
  nginx_logs:
