---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: demo-staticfiles
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/gemma-demo-static"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-staticfiles-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
